### ISSUE TITLE
chore: enable lint rules in `.eslintrc.js` and fix errors

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1891]
We have a bunch of `eslint` rules disabled in out configuration https://github.com/netlify/cli/blob/f9ec20633cd2aa22f25f19f4112b46f80562d69a/.eslintrc.js#L8

We should enable those one by one and fix related errors. This is an envelope issue for related PRs.

### TODO
- [ ] `class-methods-use-this`
- [ ] `complexity`
- [ ] `max-depth`
- [ ] `max-lines`
- [ ] `max-lines-per-function`
- [ ] `max-nested-callbacks`
- [ ] `max-statements`
- [ ] `no-param-reassign`
- [ ] `no-process-exit`
- [ ] `fp/no-class`
- [ ] `fp/no-delete`
- [ ] `fp/no-get-set`
- [ ] `fp/no-let`
- [ ] `fp/no-loops`
- [ ] `fp/no-mutating-assign`
- [ ] `fp/no-mutating-methods`
- [ ] `fp/no-mutation`
- [ ] `fp/no-proxy`
- [ ] `fp/no-this`
- [ ] `import/max-dependencies`
- [ ] `node/no-sync`
- [x] `promise/catch-or-return`
- [x] `promise/no-callback-in-promise`
- [x] `promise/no-nesting`
- [x] `promise/no-return-wrap`
- [x] `promise/prefer-await-to-callbacks`
- [x] `promise/prefer-await-to-then`
- [x] `you-dont-need-lodash-underscore/get`
- [ ] `unicorn/prefer-spread`
- [ ] `unicorn/consistent-destructuring`
- [x] `unicorn/no-array-push-push`
- [ ] `unicorn/filename-case`

**Comment by ehmicky** [comment]
Related: https://github.com/netlify/cli/issues/1437

**Comment by tinfoil-knight** [comment]
@erezrokah Can I pick up the first one?

**Comment by ehmicky** [comment]
@tinfoil-knight Please feel free to pick any of these, including `class-methods-use-this`. Thanks a lot for your help! :heart:

**Comment by tinfoil-knight** [comment]
I'm picking up `fp/no-loops` while `class-methods-use-this` is in process.
