### ISSUE TITLE
Refactor all tests to use ESM and vitest

### ISSUE THREAD

**Issue by danez** [netlify/cli#5698]
We still have some tests that use ava and commonjs, we should refactor them to use vitest and ESM instead.

There is also a new fixture runner for tests which we can use, which can make the tests also faster. But can also be done afterwards.
```[tasklist]
### Tasks
- [ ] https://github.com/netlify/cli/pull/5892
- [ ] https://github.com/netlify/cli/pull/5919
- [ ] 200.command.dev.test.cjs
- [ ] 210.command.deploy.test.cjs
- [ ] 300.command.dev.test.cjs
- [ ] 500.command.dev.test.cjs
- [ ] 600.framework-detection.test.cjs
- [ ] 610.command.env.test.cjs
- [ ] 640.command.recipes.test.cjs
```

**Comment by hereje** [comment]
Remaining test files to be migrated:

- [ ] 100.command.dev.test.cjs #5892 
- [ ] 200.command.dev.test.cjs #TBD
- [ ] 210.command.deploy.test.cjs #TBD
- [ ] 300.command.dev.test.cjs #TBD
- [ ] 500.command.dev.test.cjs #TBD
- [ ] 600.framework-detection.test.cjs #TBD
- [ ] 610.command.env.test.cjs #TBD
- [ ] 640.command.recipes.test.cjs #TBD
- [ ] 650.command.envelope.test.cjs #5919
